#!/usr/bin/env python3
"""Generate self-hosted Supabase secrets: JWT_SECRET, ANON_KEY, SERVICE_ROLE_KEY.

No third-party dependencies. Run this yourself and paste the output straight
into Railway — do not commit the generated values anywhere.

    python3 gen-supabase-keys.py            # print to stdout
    python3 gen-supabase-keys.py > keys.env # or write to a file you keep private
"""
import base64
import hashlib
import hmac
import json
import secrets
import time


def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def sign_jwt(payload: dict, secret: str) -> str:
    header = {"alg": "HS256", "typ": "JWT"}
    seg = (
        f"{b64url(json.dumps(header, separators=(',', ':')).encode())}."
        f"{b64url(json.dumps(payload, separators=(',', ':')).encode())}"
    )
    sig = hmac.new(secret.encode(), seg.encode(), hashlib.sha256).digest()
    return f"{seg}.{b64url(sig)}"


def main() -> None:
    # 48 random bytes -> ~64 char base64 secret (Supabase requires 40+).
    jwt_secret = base64.b64encode(secrets.token_bytes(48)).decode()

    iat = int(time.time())
    exp = iat + 10 * 365 * 24 * 60 * 60  # 10 years

    anon = sign_jwt({"role": "anon", "iss": "supabase", "iat": iat, "exp": exp}, jwt_secret)
    service = sign_jwt({"role": "service_role", "iss": "supabase", "iat": iat, "exp": exp}, jwt_secret)

    print("# Generated by gen-supabase-keys.py — keep private, do not commit.")
    print(f"JWT_SECRET={jwt_secret}")
    print(f"ANON_KEY={anon}")
    print(f"SERVICE_ROLE_KEY={service}")


if __name__ == "__main__":
    main()
